openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger MUVZ - Client
  description: A sample API as an example to client features in the OpenAPI 3.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://muvz.tech

paths:
  /client/listClient:
    get:
      tags:
        - listClient
      summary: Returns all client from the system that the user has access to
      description: Returns all client from the system that the user has access to
      operationId: listClient
      parameters:
        - in: query
          name: pageNo
          schema:
            type: integer
            default: 0
          required: false
          description: The number of items to skip before starting to collect the result set.
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 20
          required: false
          description: The number of items to return.
        - in: query
          name: sortBy
          schema:
            type: array
            items:
              type: string

      responses:
        '200':
          description: client response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/page"
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: "#/components/schemas/pageClient"

        '500':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generalError'


  /client/nmName/{nmName}:
    get:
      tags:
        - listClientByNmName
      summary: Returns a client based on a single name
      description: Returns a client based on a name
      operationId: listClientByName
      parameters:
        - name: nmName
          in: path
          description: nmName client
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/client'

        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'

        '500':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generalError'

components:
  schemas:
    pageClient:
      allOf:
        - $ref: '#/components/schemas/client'
        - type: object

    client:
      type: object
      properties:
        coSeqClient:
          type: number
        nmName:
          type: string
        nmNickName:
          type: string
        ddBirthday:
          type: string
          format: date
        contacts:
          type: array
          items:
            $ref: "#/components/schemas/contact"
        address:
          type: array
          items:
            $ref: "#/components/schemas/address"

    contact:
      type: object
      properties:
        coSeqContact:
          type: number
        nmTelephone:
          type: string
        nmCellphone:
          type: string
        nmEmail:
          type: string

    address:
      type: object
      properties:
        coSeqAddress:
          type: number
        nmAddress:
          type: string
        nmAddressZipCode:
          type: string
        nmAddressNumber:
          type: string
        nmAddressCityCode:
          type: string

    genericMessage:
      type: object
      properties:
        message:
          type: string

    notFound:
      type: object
      properties:
        schema:
          $ref: "#/components/schemas/genericMessage"

    generalError:
      type: object
      properties:
        schema:
          $ref: "#/components/schemas/genericMessage"

    sort:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: number

    pageable:
      type: object
      properties:
        pageNumber:
          type: number
        pageSize:
          type: number
        offset:
          type: number
        paged:
          type: boolean
        unpaged:
          type: boolean
        sort:
          $ref: '#/components/schemas/sort'

    page:
      type: object
      properties:
        totalElements:
          type: number
        totalPages:
          type: number
        last:
          type: boolean
        size:
          type: number
        number:
          type: number
        first:
          type: boolean
        numberOfElements:
          type: number
        empty:
          type: boolean
        content:
          type: array
          items:
            type: object
        pageable:
          $ref: '#/components/schemas/pageable'
        sort:
          $ref: '#/components/schemas/sort'
