spring:
  application:
    name: ms-muvz-tech

  main:
    allow-bean-definition-overriding: true

  banner:
    location: classpath:/banner.txt

  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      validationQuery: select 1
      testOnBorrow: true

    jpa:
      hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties.hibernate.format_sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true

endpoint:
  url: https://newsapi.org/v2
  context.everthing: everything
  context.top.headlines: top-headlines
  key: 9384f09f12d14caeb58a7145b77ba166


server:
  port: 8080