spring:
  application:
    name: ms-muvz-tech

  main:
    allow-bean-definition-overriding: true

  banner:
    location: classpath:/banner.txt

  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:

    jpa:
      hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties.hibernate.format_sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true

server:
  port: 8080
